from sqlalchemy import *

meta = MetaData()

choice_res_model = Table(
    'choice_res', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(20)),
    Column('AsOfDate', Date()),
    Column('Account', String(20)),
    Column('GuestName', Text()),
    Column('Arrive', String(10)),
    Column('Depart', String(10)),
    Column('Nights', String(20)),
    Column('Status', String(20)),
    Column('Rate', String(20)),
    Column('RateCode', String(20)),
    Column('Type', String(20)),
    Column('Room', String(20)),
    Column('Source', String(20)),
    Column('CRSConfNo', String(20)),
    Column('GTD', String(20)),
    Column('ReserveDate', String(20)),
    Column('ReserveTime', String(20)),
    Column('User', String(20)),
    Column('SharedAccount', String(20)),
    Column('TrackCode', String(20)),
    Column('Package', String(20)),
    Column('CancellationDate', String(10)),
    Column('CancellationTime', String(8)),
    Column('CXLUserID', String(255)),
)

choice_occ_model = Table(
    'choice_occ', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(20)),
    Column('AsOfDate', Date()),
    Column('IDS_DATE', String(20)),
    Column('Day', String(20)),
    Column('Rooms', String(10)),
    Column('OOO', String(10)),
    Column('StayOver', String(20)),
    Column('Arrivals', String(20)),
    Column('DueOut', String(20)),
    Column('Available', String(20)),
    Column('GroupBlock', String(20)),
    Column('GroupPickedUp', String(20)),
    Column('TransNGTD', String(20)),
    Column('TransGTD', String(20)),
    Column('Occupied', String(20)),
    Column('OccPercent', String(20)),
    Column('RoomRev', String(20)),
    Column('RevPAR', String(20)),
    Column('ADR', String(20)),
    Column('Ppl', String(20))
)

choice_busi_model = Table(
    'choice_busi_on_books', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(20)),
    Column('AsOfDate', Date()),
    Column('Date', String(20)),
    Column('TransientRooms', String(20)),
    Column('TransientPPL', String(10)),
    Column('GroupRooms', String(10)),
    Column('GroupPPL', String(20)),
    Column('DefiniteNotPickup', String(20)),
    Column('TentativeNotPickup', String(20)),
    Column('TotalOccupiedRooms', String(20)),
    Column('TotalPPL', String(20)),
    Column('Occ', String(20)),
    Column('COMPS', String(20)),
    Column('RoomRev', String(20)),
    Column('RevPar', String(20)),
    Column('ADR', String(20)),
)

choice_cancellation_model = Table(
    'choice_cancellation', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(55)),
    Column('pullDateId', BIGINT),
    Column('AsOfDate', Date()),
    Column('CancellationReason', String(55)),
    Column('CxlDate', String(55)),
    Column('Resv', String(55)),
    Column('RoomNights', String(55)),
    Column('RoomRev', String(55)),
)

choice_revenue_model = Table(
    'choice_revenue', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(55)),
    Column('pullDateId', BIGINT),
    Column('AsOfDate', Date()),
    Column('IDS_RATE_CODE', String(55)),
    Column('RoomNights', String(55)),
    Column('RoomNightsPer', String(55)),
    Column('RoomRevenue', String(55)),
    Column('RoomRevenuePer', String(55)),
    Column('DailyAVG', String(55)),
    Column('PTDRoomNights', String(55)),
    Column('PTDRoomNightsPer', String(55)),
    Column('PTDRoomRevenue', String(55)),
    Column('PTDRoomRevenuePer', String(55)),
    Column('PTD_AVG', String(55)),
    Column('YTDRoomNights', String(55)),
    Column('YTDRoomNightsPer', String(55)),
    Column('YTDRoomRevenue', String(55)),
    Column('YTDRoomRevenuePer', String(55)),
    Column('YTD_AVG', String(55)),
)

auto_clerk_res_model = Table(
    'auto_clerk_res', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(20)),
    Column('DateTime', String(20)),
    Column('Status', String(20)),
    Column('MyhmsConf', String(20)),
    Column('CRSConf', String(20)),
    Column('roomnumber', String(20)),
    Column('roomtype', String(20)),
    Column('rateplan', String(20)),
    Column('rate', String(20)),
    Column('Paytype', String(20)),
    Column('arrivaldate', String(20)),
    Column('departuredate', String(20)),
    Column('nights', String(20)),
    Column('guestlastname', String(20)),
    Column('guestfirstname', String(20)),
    Column('address1', Text),
    Column('address2', Text),
    Column('city', String(20)),
    Column('state', String(20)),
    Column('zip', String(20)),
    Column('country', String(20)),
    Column('phone', String(20)),
    Column('email', String(20)),
    Column('TotalRevenueforstay', String(20)),
    Column('RoomRevenueforstay', String(20)),
    Column('source', String(20)),
    Column('market', String(20)),
    Column('channel', String(20)),
    Column('companyName', String(20)),
    Column('drivingLicence', String(20))
)

auto_clerk_occ_model = Table(
    'auto_clerk_occ', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(20)),
    Column('Date', String(20)),
    Column('Rooms', String(20)),
    Column('Arrivals', String(20)),
    Column('StayOver', String(20)),
    Column('DepartToday', String(20)),
    Column('OccupRooms', String(20)),
    Column('UnusedGroupBlocks', String(20)),
    Column('Occup', String(20)),
    Column('A', String(20)),
    Column('C', String(20)),
    Column('I', String(20)),
    Column('RoomRevenue', String(20)),
    Column('ADR', String(20)),
    Column('REVPAR', String(20)),
    Column('OOORooms', String(20)),
    Column('UnusedAllotment', String(20)),
    Column('AvailRooms', String(20))
)

ihg_res_model = Table(
    'ihg_res', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(20)),
    Column('ConfirmationNumber', String(20)),
    Column('PriorityClubMember', String(20)),
    Column('GuestName', String(20)),
    Column('ArrivalDate', String(20)),
    Column('TransactionTime(GMT)', String(20)),
    Column('RateCode', String(20)),
    Column('RateCategory', String(20)),
    Column('Guaranteed', String(20)),
    Column('RoomType', String(20)),
    Column('ArrivalRoomRate', String(20)),
    Column('NumberofGuests', String(20)),
    Column('NumberofNights', String(20)),
    Column('NumberofRooms', String(20)),
    Column('PropertyName', String(20)),
    Column('ATLTM', String(20))
)

ihg_occ_model = Table(
    'ihg_occ', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(20)),
    Column('BlackoutDates', String(20)),
    Column('blank', String(20)),
    Column('ClosedtoArrival', String(20)),
    Column('Date', String(20)),
    Column('DayofWeek', String(20)),
    Column('MaximumLOS', String(20)),
    Column('MinimumLOS', String(20)),
    Column('ReservationGuaranteeRequired', String(20)),
    Column('24Hourhold', String(20)),
    Column('AverageLeadTime', String(20)),
    Column('AverageLOS', String(20)),
    Column('CancelDue', String(20)),
    Column('CancelorNoShow', String(20)),
    Column('DepositDue', String(20)),
    Column('Deposit', String(20)),
    Column('Groupremaining', String(20)),
    Column('RoomslefttoSell', String(20)),
    Column('SpecialEventSpecialRequirement', String(20)),
    Column('Paceasofdate', String(20)),
    Column('AC', String(20)),
    Column('ActualroomssoldLY', String(20)),
    Column('ADR', String(20)),
    Column('BFR', String(20)),
    Column('Groupcommitted', String(20)),
    Column('Groupcontracted', String(20)),
    Column('GroupPickupasofdate', String(20)),
    Column('Grouppickup', String(20)),
    Column('Occ', String(20)),
    Column('OVB', String(20)),
    Column('Paceasofdate1', String(20)),
    Column('Paceasofdate2', String(20)),
    Column('Pickupasofdate', String(20)),
    Column('Pickupasofdate1', String(20)),
    Column('Roomssold', String(20)),
    Column('TotalRoomsCommitted', String(20)),
)
hyatt_res_model = Table(
    'hyatt_res', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(20)),
    Column('AsOfDate', Date()),
    Column('RESV_NAME_ID', String(55)),
    Column('GUARANTEE_CODE', String(55)),
    Column('RESV_STATUS', String(55)),
    Column('ROOM', String(55)),
    Column('FULL_NAME', String(55)),
    Column('DEPARTURE', String(55)),
    Column('PERSONS', String(55)),
    Column('GROUP_NAME', String(55)),
    Column('NO_OF_ROOMS', String(55)),
    Column('ROOM_CATEGORY_LABEL', String(55)),
    Column('RATE_CODE', String(55)),
    Column('INSERT_USER', String(55)),
    Column('INSERT_DATE', String(55)),
    Column('GUARANTEE_CODE_DESC', String(55)),
    Column('COMPANY_NAME', String(55)),
    Column('TRAVEL_AGENT_NAME', String(55)),
    Column('ARRIVAL', String(55)),
    Column('NIGHTS', String(55)),
    Column('COMP_HOUSE_YN', String(55)),
    Column('SHARE_AMOUNT', String(55)),
    Column('C_T_S_NAME', String(55)),
    Column('SHORT_RESV_STATUS', String(55)),
    Column('SHARE_AMOUNT_PER_STAY', String(55)),
)

hyatt_occ_model = Table(
    'hyatt_occ', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(20)),
    Column('AsOfDate', Date()),
    Column('REVENUE', String(55)),
    Column('NO_ROOMS', String(55)),
    Column('IND_DEDUCT_ROOMS', String(55)),
    Column('IND_NON_DEDUCT_ROOMS', String(55)),
    Column('GRP_DEDUCT_ROOMS', String(55)),
    Column('GRP_NON_DEDUCT_ROOMS', String(55)),
    Column('NO_PERSONS', String(55)),
    Column('ARRIVAL_ROOMS', String(55)),
    Column('DEPARTURE_ROOMS', String(55)),
    Column('COMPLIMENTARY_ROOMS', String(55)),
    Column('HOUSE_USE_ROOMS', String(55)),
    Column('DAY_USE_ROOMS', String(55)),
    Column('NO_SHOW_ROOMS', String(55)),
    Column('INVENTORY_ROOMS', String(55)),
    Column('CONSIDERED_DATE', String(55)),
    Column('CHAR_CONSIDERED_DATE', String(55)),
    Column('IND_DEDUCT_REVENUE', String(55)),
    Column('IND_NON_DEDUCT_REVENUE', String(55)),
    Column('GRP_NON_DEDUCT_REVENUE', String(55)),
    Column('GRP_DEDUCT_REVENUE', String(55)),
    Column('OWNER_ROOMS', String(55)),
    Column('FF_ROOMS', String(55)),
    Column('CF_OOO_ROOMS', String(55)),
    Column('CF_CALC_OCC_ROOMS', String(55)),
    Column('CF_CALC_INV_ROOMS', String(55)),
    Column('CF_AVERAGE_ROOM_RATE', String(55)),
    Column('CF_OCCUPANCY', String(55)),
    Column('CF_IND_DED_REV', String(55)),
    Column('CF_IND_NON_DED_REV', String(55)),
    Column('CF_BLK_DED_REV', String(55)),
    Column('CF_BLK_NON_DED_REV', String(55))
)

pms_wise_hyatt_occ_model = Table(
    'pms_wise_hyatt_occ', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(20)),
    Column('AsOfDate', Date()),
    Column('REVENUE', String(55)),
    Column('NO_ROOMS', String(55)),
    Column('IND_DEDUCT_ROOMS', String(55)),
    Column('IND_NON_DEDUCT_ROOMS', String(55)),
    Column('GRP_DEDUCT_ROOMS', String(55)),
    Column('GRP_NON_DEDUCT_ROOMS', String(55)),
    Column('NO_PERSONS', String(55)),
    Column('ARRIVAL_ROOMS', String(55)),
    Column('DEPARTURE_ROOMS', String(55)),
    Column('COMPLIMENTARY_ROOMS', String(55)),
    Column('HOUSE_USE_ROOMS', String(55)),
    Column('DAY_USE_ROOMS', String(55)),
    Column('NO_SHOW_ROOMS', String(55)),
    Column('INVENTORY_ROOMS', String(55)),
    Column('CONSIDERED_DATE', String(55)),
    Column('CHAR_CONSIDERED_DATE', String(55)),
    Column('IND_DEDUCT_REVENUE', String(55)),
    Column('IND_NON_DEDUCT_REVENUE', String(55)),
    Column('GRP_NON_DEDUCT_REVENUE', String(55)),
    Column('GRP_DEDUCT_REVENUE', String(55)),
    Column('OWNER_ROOMS', String(55)),
    Column('FF_ROOMS', String(55)),
    Column('CF_OOO_ROOMS', String(55)),
    Column('CF_CALC_OCC_ROOMS', String(55)),
    Column('CF_CALC_INV_ROOMS', String(55)),
    Column('CF_AVERAGE_ROOM_RATE', String(55)),
    Column('CF_OCCUPANCY', String(55)),
    Column('CF_IND_DED_REV', String(55)),
    Column('CF_IND_NON_DED_REV', String(55)),
    Column('CF_BLK_DED_REV', String(55)),
    Column('CF_BLK_NON_DED_REV', String(55))
)

pms_wise_hyatt_res_model = Table(
    'pms_wise_hyatt_res', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(20)),
    Column('AsOfDate', Date()),
    Column('RESV_NAME_ID', String(55)),
    Column('GUARANTEE_CODE', String(55)),
    Column('RESV_STATUS', String(55)),
    Column('ROOM', String(55)),
    Column('FULL_NAME', String(55)),
    Column('DEPARTURE', String(55)),
    Column('PERSONS', String(55)),
    Column('GROUP_NAME', String(55)),
    Column('NO_OF_ROOMS', String(55)),
    Column('ROOM_CATEGORY_LABEL', String(55)),
    Column('RATE_CODE', String(55)),
    Column('INSERT_USER', String(55)),
    Column('INSERT_DATE', String(55)),
    Column('GUARANTEE_CODE_DESC', String(55)),
    Column('COMPANY_NAME', String(55)),
    Column('TRAVEL_AGENT_NAME', String(55)),
    Column('ARRIVAL', String(55)),
    Column('NIGHTS', String(55)),
    Column('COMP_HOUSE_YN', String(55)),
    Column('SHARE_AMOUNT', String(55)),
    Column('C_T_S_NAME', String(55)),
    Column('SHORT_RESV_STATUS', String(55)),
    Column('SHARE_AMOUNT_PER_STAY', String(55)),
)

opera_occ_model = Table(
    'opera_occ', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(20)),
    Column('AsOfDate', Date()),
    Column('REVENUE', String(55)),
    Column('NO_ROOMS', String(55)),
    Column('IND_DEDUCT_ROOMS', String(55)),
    Column('IND_NON_DEDUCT_ROOMS', String(55)),
    Column('GRP_DEDUCT_ROOMS', String(55)),
    Column('GRP_NON_DEDUCT_ROOMS', String(55)),
    Column('NO_PERSONS', String(55)),
    Column('ARRIVAL_ROOMS', String(55)),
    Column('DEPARTURE_ROOMS', String(55)),
    Column('COMPLIMENTARY_ROOMS', String(55)),
    Column('HOUSE_USE_ROOMS', String(55)),
    Column('DAY_USE_ROOMS', String(55)),
    Column('NO_SHOW_ROOMS', String(55)),
    Column('INVENTORY_ROOMS', String(55)),
    Column('CONSIDERED_DATE', String(55)),
    Column('CHAR_CONSIDERED_DATE', String(55)),
    Column('IND_DEDUCT_REVENUE', String(55)),
    Column('IND_NON_DEDUCT_REVENUE', String(55)),
    Column('GRP_NON_DEDUCT_REVENUE', String(55)),
    Column('GRP_DEDUCT_REVENUE', String(55)),
    Column('OWNER_ROOMS', String(55)),
    Column('FF_ROOMS', String(55)),
    Column('CF_OOO_ROOMS', String(55)),
    Column('CF_CALC_OCC_ROOMS', String(55)),
    Column('CF_CALC_INV_ROOMS', String(55)),
    Column('CF_AVERAGE_ROOM_RATE', String(55)),
    Column('CF_OCCUPANCY', String(55)),
    Column('CF_IND_DED_REV', String(55)),
    Column('CF_IND_NON_DED_REV', String(55)),
    Column('CF_BLK_DED_REV', String(55)),
    Column('CF_BLK_NON_DED_REV', String(55))
)

opera_res_model = Table(
    'opera_res', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(20)),
    Column('AsOfDate', Date()),
    Column('RESV_NAME_ID', String(55)),
    Column('GUARANTEE_CODE', String(55)),
    Column('RESV_STATUS', String(55)),
    Column('ROOM', String(55)),
    Column('FULL_NAME', String(55)),
    Column('DEPARTURE', String(55)),
    Column('PERSONS', String(55)),
    Column('GROUP_NAME', String(55)),
    Column('NO_OF_ROOMS', String(55)),
    Column('ROOM_CATEGORY_LABEL', String(55)),
    Column('RATE_CODE', String(55)),
    Column('INSERT_USER', String(55)),
    Column('INSERT_DATE', String(55)),
    Column('GUARANTEE_CODE_DESC', String(55)),
    Column('COMPANY_NAME', String(55)),
    Column('TRAVEL_AGENT_NAME', String(55)),
    Column('ARRIVAL', String(55)),
    Column('NIGHTS', String(55)),
    Column('COMP_HOUSE_YN', String(55)),
    Column('SHARE_AMOUNT', String(55)),
    Column('C_T_S_NAME', String(55)),
    Column('SHORT_RESV_STATUS', String(55)),
    Column('SHARE_AMOUNT_PER_STAY', String(55)),
)

hilton_occ_model = Table(
    'hilton_occ', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('AsOfDate', Date()),
    Column('pullDateId', String()),
    Column('Date', String()),
    Column('DayOfWeek', String(10)),
    Column('RoomRevenue', String()),
    Column('TotalRooms', String()),
    Column('SoldRooms', String()),
    Column('SoldRoomsWithoutComp', String()),
    Column('DownRooms', String()),
    Column('VacantRooms', String()),
    Column('CleanRooms', String()),
    Column('DirtyRooms', String()),
    Column('StayoverRooms', String()),
    Column('SameDayBookings', String()),
    Column('CompRooms', String()),
    Column('HouseRooms', String()),
    Column('ZeroRateRooms', String()),
    Column('DayUseRooms', String()),
    Column('TotalNoShows', String()),
    Column('TotalCancellations', String()),
    Column('TotalGuests', String()),
    Column('TotalGuestCertificates', String()),
    Column('ADR', String()),
    Column('ADRWithoutComplimentaryAndHouseUseRooms', String()),
    Column('OccupancyIncludingOOOCompandHouseUse', String()),
    Column('OccupancyExcludingOOOCompandHouseUse', String()),
    Column('OccupancyIncludingOOOExcludingCompandHouseUse',String()),
    Column('OccupancyExcludingOOOIncludingCompandHouseUse', String()),
    Column('RevparWithOOORooms', String()),
    Column('RevparWithoutOOORooms', String())
)

hilton_res_model = Table(
    'hilton_res', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('AsOfDate', Date()),
    Column('pullDateId', String()),
    Column('BookingDate', String()),
    Column('BookingTime', String()),
    Column('ConfirmationNumber', String()),
    Column('ExternalConfirmationNumber', String()),
    Column('PONumber', String()),
    Column('GuestName', String()),
    Column('CompanyName', String()),
    Column('ArrivalDate', String()),
    Column('DepartureDate', String()),
    Column('Nights', String()),
    Column('Adults', String()),
    Column('Children', String()),
    Column('RoomType', String()),
    Column('RatePlan', String()),
    Column('MarketSegment', String()),
    Column('LocalMarketSegment', String()),
    Column('Source', String()),
    Column('TotalRoomRate', String()),
    Column('ADR', String()),
    Column('CurrentBookingStatus', String()),
    Column('CancellationDate', String()),
    Column('CancellationTime', String()),
    Column('BookedBy', String()),
    Column('LocalFirstName', String()),
    Column('LocalLastName', String())
)


bw_guest_name_model = Table(
    'bw_guest_name', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('asOfDate', Date()),
    Column('propertyCode', String(150)),
    Column('pullDateId', String(150)),
    Column('HotelName', String(150)),
    Column('BusinessDateCaption', String(150)),
    Column('BusinessDateVal', String(150)),
    Column('PrintedCaption', String(150)),
    Column('PrintedValue', String(150)),
    Column('txtMobileKey', String(150)),
    Column('textBox13', String(150)),
    Column('textBox12', String(150)),
    Column('textBox11', String(150)),
    Column('textBox10', String(150)),
    Column('textBox9', String(150)),
    Column('textBox8', String(150)),
    Column('textBox7', String(150)),
    Column('textBox6', String(150)),
    Column('textBox5', String(150)),
    Column('textBox4', String(150)),
    Column('textBox3', String(150)),
    Column('textBox1', String(150)),
    Column('textBox15', String(150)),
    Column('textBox16', String(150)),
    Column('arrDateCaptionTextBox', String(150)),
    Column('depDateCaptionTextBox', String(150)),
    Column('guestNameCaptionTextBox', String(150)),
    Column('guestAddressCaptionTextBox', String(150)),
    Column('companyNameCaptionTextBox', String(150)),
    Column('commentsCaptionTextBox', String(150)),
    Column('adultsCaptionTextBox', String(150)),
    Column('childrenOverCaptionTextBox', String(150)),
    Column('marketSegmentCaptionTextBox', String(150)),
    Column('ratePlanCaptionTextBox', String(150)),
    Column('amountCaptionTextBox', String(150)),
    Column('iATACaptionTextBox', String(150)),
    Column('guestStatusCaptionTextBox', String(150)),
    Column('balanceCaptionTextBox', String(150)),
    Column('roomTypeCaptionTextBox', String(150)),
    Column('shareNameCaptionTextBox', String(150)),
    Column('roomCaptionTextBox', String(150)),
    Column('groupNameCaptionTextBox', String(150)),
    Column('textBox20', String(150)),
    Column('holdTypeCaptionTextBox', String(150)),
    Column('confirmationCaptionTextBox', String(150)),
    Column('textBox22', String(150)),
    Column('textBox18', String(150)),
    Column('txtAutotag', String(150)),
    Column('txtAutoTagState', String(150)),
    Column('textBox2', String(150)),
    Column('textBox19', String(150)),
    Column('textBox28', String(150)),
    Column('textBox30', String(150)),
    Column('textBox24', String(150)),
    Column('textBox31', String(150)),
    Column('arrDateDataTextBox', String(150)),
    Column('depDateDataTextBox', String(150)),
    Column('guestNameDataTextBox', String(150)),
    Column('guestAddressDataTextBox', String(150)),
    Column('guestCityStatePostalDataTextBox', String(150)),
    Column('companyNameDataTextBox', String(150)),
    Column('iATADataTextBox', String(150)),
    Column('commentsDataTextBox', String(150)),
    Column('adultsDataTextBox', String(150)),
    Column('childrenOverDataTextBox', String(150)),
    Column('marketSegmentDataTextBox', String(150)),
    Column('ratePlanDataTextBox', String(150)),
    Column('amountDataTextBox', String(150)),
    Column('roomDataTextBox', String(150)),
    Column('holdTypeDataTextBox', String(150)),
    Column('confirmationDataTextBox', String(150)),
    Column('guestStatusDataTextBox', String(150)),
    Column('groupNameDataTextBox', String(150)),
    Column('shareNameDataTextBox', String(150)),
    Column('balanceDataTextBox', String(150)),
    Column('roomTypeDataTextBox', String(150)),
    Column('textBox17', String(150)),
    Column('textBox21', String(150)),
    Column('CRSConfirmationDataTextBox', String(150)),
    Column('textBox23', String(150)),
    Column('textBox25', String(150)),
    Column('TxtdataAutoTagNumber', String(150)),
    Column('txtdataAutoTagState', String(150)),
    Column('textBox14', String(150)),
    Column('CRSConfirmationData2TextBox', String(150)),
    Column('textBox26', String(150)),
    Column('textBox27', String(150)),
    Column('textBox29', String(150)),
    Column('loyaltyNumberTextBox', String(150)),
    Column('textBox32', String(150))
)
bw_res_agent_model = Table(
    'bw_res_agent', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('asOfDate', Date()),
    Column('propertyCode', String(150)),
    Column('pullDateId', String(150)),
    Column('HotelName', String(150)),
    Column('PrintedValue', String(150)),
    Column('PrintedCaption', String(150)),
    Column('BusinessDateVal', String(150)),
    Column('BusinessDateCaption', String(150)),
    Column('textBox66', String(150)),
    Column('textBox68', String(150)),
    Column('textBox60', String(150)),
    Column('textBox55', String(150)),
    Column('textBox8', String(150)),
    Column('textBox92', String(150)),
    Column('textBox90', String(150)),
    Column('textBox88', String(150)),
    Column('textBox86', String(150)),
    Column('textBox83', String(150)),
    Column('textBox89', String(150)),
    Column('textBox91', String(150)),
    Column('textBox87', String(150)),
    Column('textBox93', String(150)),
    Column('textBox94', String(150)),
    Column('textBox85', String(150)),
    Column('textBox84', String(150)),
    Column('textBox96', String(150)),
    Column('textBox17', String(150)),
    Column('textBox37', String(150)),
    Column('textBox44', String(150)),
    Column('textBox43', String(150)),
    Column('textBox3', String(150)),
    Column('textBox5', String(150)),
    Column('textBox6', String(150)),
    Column('textBox7', String(150)),
    Column('textBox9', String(150)),
    Column('textBox10', String(150)),
    Column('textBox11', String(150)),
    Column('textBox12', String(150)),
    Column('textBox13', String(150)),
    Column('textBox14', String(150)),
    Column('textBox16', String(150)),
    Column('textBox15', String(150)),
    Column('textBox4', String(150)),
)
bw_res_fore_model = Table(
    'bw_res_forecast', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('asOfDate', Date()),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(20)),
    Column('textBox37', String(150)),
    Column('textBox11', String(150)),
    Column('textBox40', String(150)),
    Column('textBox7', String(150)),
    Column('textBox41', String(150)),
    Column('textBox12', String(150)),
    Column('textBox42', String(150)),
    Column('textBox16', String(150)),
    Column('textBox43', String(150)),
    Column('textBox20', String(150)),
    Column('textBox44', String(150)),
    Column('textBox24', String(150)),
    Column('textBox25', String(150)),
    Column('textBox85', String(150)),
    Column('textBox86', String(150)),
    Column('textBox46', String(150)),
    Column('textBox26', String(150)),
    Column('textBox47', String(150)),
    Column('textBox27', String(150)),
    Column('textBox48', String(150)),
    Column('textBox28', String(150)),
    Column('textBox49', String(150)),
    Column('textBox29', String(150)),
    Column('textBox79', String(150)),
    Column('textBox80', String(150)),
    Column('textBox50', String(150)),
    Column('textBox30', String(150)),
    Column('textBox51', String(150)),
    Column('textBox31', String(150)),
    Column('textBox52', String(150)),
    Column('textBox32', String(150)),
    Column('textBox53', String(150)),
    Column('textBox33', String(150)),
    Column('textBox54', String(150)),
    Column('textBox34', String(150)),
    Column('textBox55', String(150)),
    Column('textBox35', String(150)),
    Column('textBox56', String(150)),
    Column('textBox36', String(150)),
    Column('textBox57', String(150)),
    Column('textBox38', String(150)),
    Column('textBox58', String(150)),
    Column('textBox60', String(150)),
    Column('textBox61', String(150)),
    Column('textBox62', String(150)),
    Column('textBox63', String(150)),
    Column('textBox64', String(150)),
    Column('textBox65', String(150)),
    Column('textBox87', String(150)),
    Column('textBox66', String(150)),
    Column('textBox67', String(150)),
    Column('textBox68', String(150)),
    Column('textBox69', String(150)),
    Column('textBox81', String(150)),
    Column('textBox70', String(150)),
    Column('textBox71', String(150)),
    Column('textBox72', String(150)),
    Column('textBox73', String(150)),
    Column('textBox74', String(150)),
    Column('textBox75', String(150)),
    Column('textBox76', String(150)),
    Column('textBox77', String(150)),
    Column('textBox181', String(150)),
    Column('textBox136', String(150)),
    Column('textBox185', String(150)),
    Column('textBox130', String(150)),
    Column('textBox186', String(150)),
    Column('textBox139', String(150)),
    Column('textBox189', String(150)),
    Column('textBox145', String(150)),
    Column('textBox190', String(150)),
    Column('textBox151', String(150)),
    Column('textBox191', String(150)),
    Column('textBox159', String(150)),
    Column('textBox192', String(150)),
    Column('textBox160', String(150)),
    Column('textBox88', String(150)),
    Column('textBox89', String(150)),
    Column('textBox193', String(150)),
    Column('textBox161', String(150)),
    Column('textBox194', String(150)),
    Column('textBox164', String(150)),
    Column('textBox195', String(150)),
    Column('textBox165', String(150)),
    Column('textBox196', String(150)),
    Column('textBox166', String(150)),
    Column('textBox82', String(150)),
    Column('textBox83', String(150)),
    Column('textBox197', String(150)),
    Column('textBox169', String(150)),
    Column('textBox198', String(150)),
    Column('textBox170', String(150)),
    Column('textBox199', String(150)),
    Column('textBox171', String(150)),
    Column('textBox200', String(150)),
    Column('textBox174', String(150)),
    Column('textBox201', String(150)),
    Column('textBox175', String(150)),
    Column('textBox202', String(150)),
    Column('textBox176', String(150)),
    Column('textBox203', String(150)),
    Column('textBox179', String(150)),
    Column('textBox204', String(150)),
    Column('textBox180', String(150)),
    Column('textBox2', String(150)),
    Column('textBox4', String(150)),
    Column('textBox5', String(150)),
    Column('textBox6', String(150)),
    Column('textBox8', String(150)),
    Column('textBox9', String(150)),
    Column('textBox10', String(150)),
    Column('textBox90', String(150)),
    Column('textBox13', String(150)),
    Column('textBox14', String(150)),
    Column('textBox15', String(150)),
    Column('textBox17', String(150)),
    Column('textBox84', String(150)),
    Column('textBox18', String(150)),
    Column('textBox19', String(150)),
    Column('textBox21', String(150)),
    Column('textBox22', String(150)),
    Column('textBox23', String(150)),
    Column('textBox39', String(150)),
    Column('textBox59', String(150)),
    Column('textBox78', String(150)),
)
bw_room_maintenance_ooo_model = Table(
    'bw_room_maintenance_ooo', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('asOfDate', Date()),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(20)),
    Column('PrintedValue', String(150)),
    Column('PrintedCaption', String(150)),
    Column('BusinessDateVal', String(150)),
    Column('BusinessDateCaption', String(150)),
    Column('HotelName', String(150)),
    Column('textBox25', String(150)),
    Column('textBox26', String(150)),
    Column('textBox1', String(150)),
    Column('textBox2', String(150)),
    Column('textBox3', String(150)),
    Column('textBox4', String(150)),
    Column('textBox5', String(150)),
    Column('textBox6', String(150)),
    Column('textBox11', String(150)),
    Column('textBox12', String(150)),
    Column('textBox7', String(150)),
    Column('textBox8', String(150)),
    Column('textBox9', String(150)),
    Column('textBox10', String(150)),
)

mst_reservation_model = Table(
    'mst_reservation', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('propertyId', BIGINT()),
    Column('pullDateId', BIGINT()),
    Column('AsOfDate', Date()),
    Column('RoomType', String(255)),
    Column('RoomNo', Integer()),
    Column('StayDate', Date()),
    Column('RateCode', String(255)),
    Column('RateCodeDescript', String(255)),
    Column('MarketSegment', String(255)),
    Column('Source', String(255)),
    Column('BookingDate', Date()),
    Column('BookingTime', Time()),
    Column('Company', String(255)),
    Column('Pace', String(20)),
    Column('RoomNight', Integer()),
    Column('Revenue', DECIMAL(18, 2)),
    Column('Rate', DECIMAL(18, 2)),
    Column('ADR', String(255)),
    Column('PayType', String(255)),
    Column('LeadTime', Integer()),
    Column('ForecastType', String(255)),
    Column('LOS', Integer()),
    Column('ExtendedStay1', Integer()),
    Column('ExtendedStay2', Integer()),
    Column('ExtendedStay3', Integer()),
    Column('ExtendedStay4', Integer()),
    Column('Account', String(255)),
    Column('Status', String(255)),
    Column('ForecastTypeRevenue', String(255)),
    Column('GuestName', String(255)),
    Column('GuestType', String(255)),
    Column('ArrivalDate', Date()),
    Column('DepartureDate', Date()),
    Column('LOS1', Integer()),
    Column('LOS2', Integer()),
    Column('LOS3', Integer()),
    Column('LOS4', Integer()),
    Column('LOS5', Integer()),
    Column('LOS6', Integer()),
    Column('User', String(255)),
    Column('BarBased', String(255)),
    Column('TravelAgent', String(255)),
    Column('ModifiedUser', String(255)),
    Column('CombinedChannel', String(255)),
    Column('CTSName', String(255)),
    Column('Intermediaries', String(255)),
    Column('GroupName', String(255)),
    Column('LOSDetails', Integer()),
    Column('ArrivalLOS1', Integer()),
    Column('ArrivalLOS2', Integer()),
    Column('ArrivalLOS3Plus', Integer()),
    Column('MarketSegmentCategory', String(255)),
    Column('MarketSegmentPrefix', String(255)),
    Column('ResvNameID', String(255)),
    Column('CancellationDate', Date()),
    Column('CancellationTime', Time()),
    Column('CancellationBy', String(255)),
    Column('RefResNo', String(255)),
    Column('EventID', Integer()),
    Column('channelpartner', String(267))
)

copy_mst_reservation_model = Table(
    'copy_mst_reservation', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('propertyId', BIGINT()),
    Column('pullDateId', BIGINT()),
    Column('AsOfDate', Date()),
    Column('RoomType', String(255)),
    Column('RoomNo', Integer()),
    Column('StayDate', Date()),
    Column('RateCode', String(255)),
    Column('RateCodeDescript', String(255)),
    Column('MarketSegment', String(255)),
    Column('Source', String(255)),
    Column('BookingDate', Date()),
    Column('BookingTime', Time()),
    Column('Company', String(255)),
    Column('Pace', String(20)),
    Column('RoomNight', Integer()),
    Column('Revenue', DECIMAL(18, 2)),
    Column('Rate', DECIMAL(18, 2)),
    Column('ADR', String(255)),
    Column('PayType', String(255)),
    Column('LeadTime', Integer()),
    Column('ForecastType', String(255)),
    Column('LOS', Integer()),
    Column('ExtendedStay1', Integer()),
    Column('ExtendedStay2', Integer()),
    Column('ExtendedStay3', Integer()),
    Column('ExtendedStay4', Integer()),
    Column('Account', String(255)),
    Column('Status', String(255)),
    Column('ForecastTypeRevenue', String(255)),
    Column('GuestName', String(255)),
    Column('GuestType', String(255)),
    Column('ArrivalDate', Date()),
    Column('DepartureDate', Date()),
    Column('LOS1', Integer()),
    Column('LOS2', Integer()),
    Column('LOS3', Integer()),
    Column('LOS4', Integer()),
    Column('LOS5', Integer()),
    Column('LOS6', Integer()),
    Column('User', String(255)),
    Column('BarBased', String(255)),
    Column('TravelAgent', String(255)),
    Column('ModifiedUser', String(255)),
    Column('CombinedChannel', String(255)),
    Column('CTSName', String(255)),
    Column('Intermediaries', String(255)),
    Column('GroupName', String(255)),
    Column('LOSDetails', Integer()),
    Column('ArrivalLOS1', Integer()),
    Column('ArrivalLOS2', Integer()),
    Column('ArrivalLOS3Plus', Integer()),
    Column('MarketSegmentCategory', String(255)),
    Column('MarketSegmentPrefix', String(255)),
    Column('ResvNameID', String(255)),
    Column('CancellationDate', Date()),
    Column('CancellationTime', Time()),
    Column('CancellationBy', String(255)),
    Column('RefResNo', String(255)),
    Column('EventID', Integer()),
    Column('channelpartner', String(267))
)

mst_current_data_res_model = Table(
    'mst_current_date_reservation', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('propertyId', BIGINT()),
    Column('pullDateId', BIGINT()),
    Column('AsOfDate', Date()),
    Column('RoomType', String(255)),
    Column('RoomNo', Integer()),
    Column('StayDate', Date()),
    Column('RateCode', String(255)),
    Column('RateCodeDescript', String(255)),
    Column('MarketSegment', String(255)),
    Column('Source', String(255)),
    Column('BookingDate', Date()),
    Column('BookingTime', Time()),
    Column('Company', String(255)),
    Column('Pace', String(20)),
    Column('RoomNight', Integer()),
    Column('Revenue', DECIMAL(18, 2)),
    Column('Rate', DECIMAL(18, 2)),
    Column('ADR', String(255)),
    Column('PayType', String(255)),
    Column('LeadTime', Integer()),
    Column('ForecastType', String(255)),
    Column('LOS', Integer()),
    Column('ExtendedStay1', Integer()),
    Column('ExtendedStay2', Integer()),
    Column('ExtendedStay3', Integer()),
    Column('ExtendedStay4', Integer()),
    Column('Account', String(255)),
    Column('Status', String(255)),
    Column('ForecastTypeRevenue', String(255)),
    Column('GuestName', String(255)),
    Column('GuestType', String(255)),
    Column('ArrivalDate', Date()),
    Column('DepartureDate', Date()),
    Column('LOS1', Integer()),
    Column('LOS2', Integer()),
    Column('LOS3', Integer()),
    Column('LOS4', Integer()),
    Column('LOS5', Integer()),
    Column('LOS6', Integer()),
    Column('User', String(255)),
    Column('BarBased', String(255)),
    Column('TravelAgent', String(255)),
    Column('ModifiedUser', String(255)),
    Column('CombinedChannel', String(255)),
    Column('CTSName', String(255)),
    Column('Intermediaries', String(255)),
    Column('GroupName', String(255)),
    Column('LOSDetails', Integer()),
    Column('ArrivalLOS1', Integer()),
    Column('ArrivalLOS2', Integer()),
    Column('ArrivalLOS3Plus', Integer()),
    Column('MarketSegmentCategory', String(255)),
    Column('MarketSegmentPrefix', String(255)),
    Column('ResvNameID', String(255)),
    Column('CancellationDate', Date()),
    Column('CancellationTime', Time()),
    Column('CancellationBy', String(255)),
    Column('RefResNo', String(255)),
    Column('EventID', Integer()),
    Column('RunTime', Time())
)

hotel_key_occ_model = Table(
    'hotel_key_occ', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(20)),
    Column('AsOfDate', Date()),
    Column('Date', String(55)),
    Column('DayOfWeek', String(55)),
    Column('Inventory', String(55)),
    Column('Down', String(55)),
    Column('StayOvers', String(55)),
    Column('FutureStayOvers', String(55)),
    Column('Arrivals', String(55)),
    Column('Departures', String(55)),
    Column('ProjectedDepartures', String(55)),
    Column('Available', String(55)),
    Column('GroupAllocations', String(55)),
    Column('GroupReservations', String(55)),
    Column('Guaranteed', String(55)),
    Column('NonGuaranteed', String(55)),
    Column('Reserved', String(55)),
    Column('OccupancyOOS', String(55)),
    Column('Occupancy', String(55)),
    Column('ConfirmedRevenue', String(55)),
    Column('ProjectedRevenue', String(55)),
    Column('RevPAR', String(55)),
    Column('ADR', String(55)),
)

hotel_key_res_model = Table(
    'hotel_key_res', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(20)),
    Column('AsOfDate', Date()),
    Column('BookingInfo', String(55)),
    Column('BookingTime', String(55)),
    Column('ConfirmationNo', String(55)),
    Column('GuestName', String(55)),
    Column('ArrivalDate', String(55)),
    Column('Nights', String(55)),
    Column('RoomType', String(55)),
    Column('Source', String(55)),
    Column('RateCode', String(55)),
    Column('RoomRent', String(55)),
    Column('Status', String(55)),
    Column('CancellationDate', String(55)),
    Column('BookedBy', String(55)),
)

pms_wise_hotel_key_res = Table(
    'pms_wise_hotel_key_res', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(20)),
    Column('AsOfDate', Date()),
    Column('BookingInfo', String(55)),
    Column('BookingTime', String(55)),
    Column('ConfirmationNo', String(55)),
    Column('GuestName', String(55)),
    Column('ArrivalDate', String(55)),
    Column('Nights', String(55)),
    Column('RoomType', String(55)),
    Column('Source', String(55)),
    Column('RateCode', String(55)),
    Column('RoomRent', String(55)),
    Column('Status', String(55)),
    Column('CancellationDate', String(55)),
    Column('BookedBy', String(55))
)

dailydata_transaction_model = Table(
    'dailydata_transaction', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('propertyId', BIGINT()),
    Column('pullDateId', BIGINT()),
    Column('AsOfDate', Date()),
    Column('Dates', Date()),
    Column('Inventory', Integer()),
    Column('RoomSold', Integer()),
    Column('TotalRevenue', DECIMAL(18, 2)),
    Column('ADR', DECIMAL(18, 2)),
    Column('TotalOccupancy', DECIMAL(18, 2)),
    Column('AvailableOccupancy', DECIMAL(18, 2)),
    Column('RevPAR', DECIMAL(18, 2)),
    Column('Occperc', DECIMAL(18, 2)),
    Column('OutOfOrder', Integer()),
    Column('RoomsOfAvailable', Integer()),
    Column('DayOfWeek', String(17)),
    Column('WeekType', String(60)),
    Column('GroupADR', DECIMAL(18, 2)),
    Column('GroupBlock', Integer()),
    Column('GroupOTB', Integer()),
    Column('GroupRevenue', DECIMAL(18, 2)),
    Column('TransientRoomSold', Integer()),
    Column('TransientRevenue', DECIMAL(18, 2)),
    Column('TransientADR', DECIMAL(18, 2)),
    Column('LYTotalInventory', Integer()),
    Column('LYTotalRoomSold', Integer()),
    Column('LYTotalRevenue', DECIMAL(18, 2)),
    Column('LYTotalADR', DECIMAL(18, 2)),
    Column('LYTotalOccupancy', DECIMAL(18, 2)),
    Column('LYTotalRevPar', DECIMAL(18, 2)),
    Column('LYTotalOccPerc', DECIMAL(18, 2)),
    Column('YestDayInventory', Integer()),
    Column('YestDayRoomSold', Integer()),
    Column('YestDayRevenue', DECIMAL(18, 2)),
    Column('YestDayADR', DECIMAL(18, 2)),
    Column('YestDayOccupancy', DECIMAL(18, 2)),
    Column('YestDayRevPar', DECIMAL(18, 2)),
    Column('YestDayOccPerc', DECIMAL(18, 2)),
    Column('LYPaceInventory', Integer()),
    Column('LYPaceRoomSold', Integer()),
    Column('LYPaceRevenue', DECIMAL(18, 2)),
    Column('LYPaceADR', DECIMAL(18, 2)),
    Column('LYPaceOccupancy', DECIMAL(18, 2)),
    Column('LYPaceRevPar', DECIMAL(18, 2)),
    Column('LYPaceOccPerc', DECIMAL(18, 2))
)

temp_dailydata_transaction_model = Table(
    'temp_dailydata_transaction', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('propertyId', BIGINT()),
    Column('pullDateId', BIGINT()),
    Column('AsOfDate', Date()),
    Column('Dates', Date()),
    Column('Inventory', Integer()),
    Column('RoomSold', Integer()),
    Column('TotalRevenue', DECIMAL(18, 2)),
    Column('ADR', DECIMAL(18, 2)),
    Column('TotalOccupancy', DECIMAL(18, 2)),
    Column('AvailableOccupancy', DECIMAL(18, 2)),
    Column('RevPAR', DECIMAL(18, 2)),
    Column('Occperc', DECIMAL(18, 2)),
    Column('OutOfOrder', Integer()),
    Column('RoomsOfAvailable', Integer()),
    Column('DayOfWeek', String(17)),
    Column('WeekType', String(60)),
    Column('GroupADR', DECIMAL(18, 2)),
    Column('GroupBlock', Integer()),
    Column('GroupOTB', Integer()),
    Column('GroupRevenue', DECIMAL(18, 2)),
    Column('TransientRoomSold', Integer()),
    Column('TransientRevenue', DECIMAL(18, 2)),
    Column('TransientADR', DECIMAL(18, 2)),
    Column('LYTotalInventory', Integer()),
    Column('LYTotalRoomSold', Integer()),
    Column('LYTotalRevenue', DECIMAL(18, 2)),
    Column('LYTotalADR', DECIMAL(18, 2)),
    Column('LYTotalOccupancy', DECIMAL(18, 2)),
    Column('LYTotalRevPar', DECIMAL(18, 2)),
    Column('LYTotalOccPerc', DECIMAL(18, 2)),
    Column('YestDayInventory', Integer()),
    Column('YestDayRoomSold', Integer()),
    Column('YestDayRevenue', DECIMAL(18, 2)),
    Column('YestDayADR', DECIMAL(18, 2)),
    Column('YestDayOccupancy', DECIMAL(18, 2)),
    Column('YestDayRevPar', DECIMAL(18, 2)),
    Column('YestDayOccPerc', DECIMAL(18, 2)),
    Column('LYPaceInventory', Integer()),
    Column('LYPaceRoomSold', Integer()),
    Column('LYPaceRevenue', DECIMAL(18, 2)),
    Column('LYPaceADR', DECIMAL(18, 2)),
    Column('LYPaceOccupancy', DECIMAL(18, 2)),
    Column('LYPaceRevPar', DECIMAL(18, 2)),
    Column('LYPaceOccPerc', DECIMAL(18, 2)),
    Column('UserNotes', Text())
)

# SNP - Annual Summary
snp_annsmry_on_the_book_model = Table(
    'snp_annsmry_on_the_book', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('AsOfDate', Date()),
    Column('year', Integer()),
    Column('month', String(17)),
    Column('occ', DECIMAL(18, 2)),
    Column('rms', Integer()),
    Column('adr', DECIMAL(18, 2)),
    Column('rev', DECIMAL(18, 2)),
)

# SNP - Annual Summary
snp_annsmry_cancellation_model = Table(
    'snp_annsmry_cancellation', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('AsOfDate', Date()),
    Column('year', Integer()),
    Column('month', String(17)),
    Column('occ', DECIMAL(18, 2)),
    Column('rms', Integer()),
    Column('adr', DECIMAL(18, 2)),
    Column('rev', DECIMAL(18, 2)),
    Column('inv', Integer()),
    Column('avgleadtime', DECIMAL(18, 2)),
    Column('unsoldrms', Integer())
)

snp_annsmry_cancellation_total_ly_model = Table(
    'snp_annsmry_cancellation_total_ly', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('AsOfDate', Date()),
    Column('year', Integer()),
    Column('month', String(17)),
    Column('occ', DECIMAL(18, 2)),
    Column('rms', Integer()),
    Column('adr', DECIMAL(18, 2)),
    Column('rev', DECIMAL(18, 2)),
    Column('inv', Integer())
)

snp_annsmry_cancellation_stly_model = Table(
    'snp_annsmry_cancellation_stly', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('AsOfDate', Date()),
    Column('year', Integer()),
    Column('month', String(17)),
    Column('occ', DECIMAL(18, 2)),
    Column('rms', Integer()),
    Column('adr', DECIMAL(18, 2)),
    Column('rev', DECIMAL(18, 2)),
    Column('inv', Integer())
)

snp_annsmry_total_ly_model = Table(
    'snp_annsmry_total_ly', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('AsOfDate', Date()),
    Column('year', Integer()),
    Column('month', String(17)),
    Column('occ', DECIMAL(18, 2)),
    Column('rms', Integer()),
    Column('adr', DECIMAL(18, 2)),
    Column('rev', DECIMAL(18, 2)),
)

snp_annsmry_net_stly_model = Table(
    'snp_annsmry_net_stly', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('AsOfDate', Date()),
    Column('year', Integer()),
    Column('month', String(17)),
    Column('occ', DECIMAL(18, 2)),
    Column('rms', Integer()),
    Column('adr', DECIMAL(18, 2)),
    Column('rev', DECIMAL(18, 2)),
)

snp_annsmry_budget_model = Table(
    'snp_annsmry_budget', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('AsOfDate', Date()),
    Column('year', Integer()),
    Column('month', String(17)),
    Column('occ', DECIMAL(18, 2)),
    Column('rms', Integer()),
    Column('adr', DECIMAL(18, 2)),
    Column('rev', DECIMAL(18, 2)),
)

# SNP - Forecast
snp_fc_spider_model = Table(
    'snp_fc_spider', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('AsOfDate', Date()),
    Column('year', Integer()),
    Column('month', String(17)),
    Column('occ', DECIMAL(18, 2)),
    Column('rms', Integer()),
    Column('adr', DECIMAL(18, 2)),
    Column('rev', DECIMAL(18, 2)),
    Column('var', DECIMAL(18, 2)),
)

snp_fc_ml_model = Table(
    'snp_fc_ml', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('AsOfDate', Date()),
    Column('year', Integer()),
    Column('month', String(17)),
    Column('occ', DECIMAL(18, 2)),
    Column('rms', Integer()),
    Column('adr', DECIMAL(18, 2)),
    Column('rev', DECIMAL(18, 2)),
    Column('var', DECIMAL(18, 2)),
)

# SNP - Forecast
snp_fc_ema_v2_model = Table(
    'snp_fc_ema_v2', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('AsOfDate', Date()),
    Column('year', Integer()),
    Column('month', String(17)),
    Column('occ', DECIMAL(18, 2)),
    Column('rms', Integer()),
    Column('adr', DECIMAL(18, 2)),
    Column('rev', DECIMAL(18, 2)),
    Column('var', DECIMAL(18, 2)),
)

snp_fc_rms_model = Table(
    'snp_fc_rms', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('AsOfDate', Date()),
    Column('year', Integer()),
    Column('month', String(17)),
    Column('occ', DECIMAL(18, 2)),
    Column('rms', Integer()),
    Column('adr', DECIMAL(18, 2)),
    Column('rev', DECIMAL(18, 2)),
    Column('var', DECIMAL(18, 2)),
)

snp_fc_user_model = Table(
    'snp_fc_user', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('AsOfDate', Date()),
    Column('year', Integer()),
    Column('month', String(17)),
    Column('occ', DECIMAL(18, 2)),
    Column('rms', Integer()),
    Column('adr', DECIMAL(18, 2)),
    Column('rev', DECIMAL(18, 2)),
    Column('var', DECIMAL(18, 2)),
)

# SNP - Transient / Group
snp_tg_transient_model = Table(
    'snp_tg_transient', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('AsOfDate', Date()),
    Column('year', Integer()),
    Column('month', String(17)),
    Column('occ', DECIMAL(18, 2)),
    Column('rms', Integer()),
    Column('adr', DECIMAL(18, 2)),
    Column('rev', DECIMAL(18, 2)),
)

snp_tg_transient_last_year_model = Table(
    'snp_tg_transient_last_year', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('AsOfDate', Date()),
    Column('year', Integer()),
    Column('month', String(17)),
    Column('occ', DECIMAL(18, 2)),
    Column('rms', Integer()),
    Column('adr', DECIMAL(18, 2)),
    Column('rev', DECIMAL(18, 2)),
)

snp_tg_group_model = Table(
    'snp_tg_group', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('AsOfDate', Date()),
    Column('year', Integer()),
    Column('month', String(17)),
    Column('occ', DECIMAL(18, 2)),
    Column('rms', Integer()),
    Column('adr', DECIMAL(18, 2)),
    Column('rev', DECIMAL(18, 2)),
    Column('blk', Integer())
)

snp_tg_group_last_year_model = Table(
    'snp_tg_group_last_year', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('AsOfDate', Date()),
    Column('year', Integer()),
    Column('month', String(17)),
    Column('occ', DECIMAL(18, 2)),
    Column('rms', Integer()),
    Column('adr', DECIMAL(18, 2)),
    Column('rev', DECIMAL(18, 2)),
    Column('blk', Integer())
)

# SNP - Pick Up
snp_pickup_one_day_model = Table(
    'snp_pickup_one_day', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('AsOfDate', Date()),
    Column('year', Integer()),
    Column('month', String(17)),
    Column('occ', DECIMAL(18, 2)),
    Column('rms', Integer()),
    Column('adr', DECIMAL(18, 2)),
    Column('rev', DECIMAL(18, 2)),
)

snp_pickup_one_day_forcast_change_model = Table(
    'snp_pickup_one_day_forcast_change', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('AsOfDate', Date()),
    Column('year', Integer()),
    Column('month', String(17)),
    Column('occ', DECIMAL(18, 2)),
    Column('rms', Integer()),
    Column('adr', DECIMAL(18, 2)),
    Column('rev', DECIMAL(18, 2)),
)

snp_pickup_seven_day_model = Table(
    'snp_pickup_seven_day', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('AsOfDate', Date()),
    Column('year', Integer()),
    Column('month', String(17)),
    Column('occ', DECIMAL(18, 2)),
    Column('rms', Integer()),
    Column('adr', DECIMAL(18, 2)),
    Column('rev', DECIMAL(18, 2)),
)

snp_pickup_seven_day_forcast_change_model = Table(
    'snp_pickup_seven_day_forcast_change', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('AsOfDate', Date()),
    Column('year', Integer()),
    Column('month', String(17)),
    Column('occ', DECIMAL(18, 2)),
    Column('rms', Integer()),
    Column('adr', DECIMAL(18, 2)),
    Column('rev', DECIMAL(18, 2)),
)

# SNP - Reservation Activity
snp_annsmry_reservation_activity_model = Table(
    'snp_annsmry_reservation_activity', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('AsOfDate', Date()),
    Column('RateCode', String(17)),
    Column('RateCodeDescription', String(17)),
    Column('Company', Text()),
    Column('GuestName', Text()),
    Column('ArrivalDate', Date()),
    Column('RoomNight', Integer()),
    Column('Status', String(17)),
    Column('Source', String(17)),
    Column('RoomType', String(17)),
    Column('User', String(100)),
    Column('BookingDate', String(17))
)

# SNP - Booking Pace
snp_bp_bookingpace_model = Table(
    'snp_bp_bookingpace', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('AsOfDate', Date()),
    Column('Dates', Date()),
    Column('TotalRevenueCurrentYear', DECIMAL(18, 2)),
    Column('TotalRevenuePreviousYear', DECIMAL(18, 2)),
    Column('TotalRMSCurrentYear', Integer()),
    Column('TotalRMSPreviousYear', Integer()),
    Column('TotalADRCurrentYear', DECIMAL(18, 4)),
    Column('TotalADRPreviousYear', DECIMAL(18, 4))
)

events_model = Table(
    'rev_all_events', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(55)),
    Column('pullDateId', BIGINT()),
    Column("AsOfDate", Date()),
    Column('event_id', String(55)),
    Column("title", String(161)),
    Column('description', Text()),
    Column("category", String(255)),
    Column("labels", String(255)),
    Column("rank", Integer()),
    Column("local_rank", Integer()),
    Column("phq_attendance", Integer()),
    Column('type', String(255)),
    Column('start_date', DateTime()),
    Column('end_date', DateTime()),
    Column('updated', DateTime()),
    Column('timezone', String(255)),
    Column('geo_lat', String(255)),
    Column('geo_long', String(255)),
    Column('place_hierarchies', String(255)),
    Column('state', String(255)),
    Column('private', Boolean())
)

tra_RateShop_model = Table(
    'tra_rate_shop', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('RateShopScheduleID', BIGINT()),
    Column('AsOfDate', Date()),
    Column('DayOfWeek', String(15)),
    Column("PropertyCode", String(15)),
    Column('CompetitorID', Integer()),
    Column("CheckInDate", Date()),
    Column("Rate", DECIMAL(18, 2)),
    Column("Discount", DECIMAL(18, 2)),
    Column("MemberDiscount", DECIMAL(18, 2)),
    Column("Channel", String(65)),
    Column('Guests', Integer()),
    Column('LOS', Integer()),
    Column('EventIDs', String(135)),
    Column('RoomType', Text()),
    Column('IsSelf', String(15)),
    Column('IsLowestRate', String(15)),
    Column('IsBarRate', String(15)),
)

tra_RateShopSchedule_model = Table(
    'tra_RateShopSchedule', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('RateShopScheduleID', BIGINT()),
    Column('PropertyID', BIGINT()),
    Column('PropertyCode', String(10)),
    Column('AsOfDate', Date()),
    Column("RSFrequencyType_Term", String(65)),
    Column('RSFrequencyCount', Integer()),
    Column("TimeOfRateShop", Integer()),
    Column("CheckInDate", DateTime()),
    Column("CheckOutDate", DateTime()),
    Column("Guests", Integer()),
    Column("LOS", Integer()),
    Column('ScheduleOn', DateTime()),
    Column('ScheduleBy', Integer()),
    Column('IsCustomRequest', Boolean()),
    Column('RequestedOn', DateTime()),
    Column('RequestedBy', Integer()),
    Column('Status_Term', String(65)),
)

rs_history_rate_shop_model = Table(
    'rs_history_rate_shop', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('RateShopScheduleID', BIGINT()),
    Column('AsOfDate', Date()),
    Column('DayOfWeek', String(15)),
    Column("PropertyCode", String(15)),
    Column('CompetitorID', Integer()),
    Column("CheckInDate", Date()),
    Column("Rate", DECIMAL(18, 2)),
    Column("Discount", DECIMAL(18, 2)),
    Column("MemberDiscount", DECIMAL(18, 2)),
    Column("Channel", String(65)),
    Column('Guests', Integer()),
    Column('LOS', Integer()),
    Column('EventIDs', String(135)),
    Column('RoomType', Text()),
    Column('IsSelf', String(15)),
    Column('IsLowestRate', String(15)),
    Column('IsBarRate', String(15)),
)

widget_pickup_model = Table(
    'widget_pickup', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('AsOfDate', Date()),
    Column('Date', Date()),
    Column('Day_Diff', String(10)),
    Column('Rms_Forecast', String(10)),
    Column('Total_Booking', String(10)),
    Column('DBA_90', String(10)),
    Column('PU_90', String(10)),
    Column('DBA_60', String(10)),
    Column('PU_60', String(10)),
    Column('DBA_30', String(10)),
    Column('PU_30', String(10)),
    Column('DBA_14', String(10)),
    Column('PU_14', String(10)),
    Column('DBA_07', String(10)),
    Column('PU_07', String(10)),
    Column('DBA_03', String(10)),
    Column('PU_03', String(10)),
    Column('DBA_01', String(10)),
    Column('PU_01', String(10)),
    Column('DBA_00', String(10)),
    Column('PU_00', String(10)),
    Column('Final', String(10))
)

snp_dbd_forecast_model = Table(
    'snp_dbd_forecast', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('AsOfDate', Date()),
    Column('Date', Date()),
    Column('Occupancy', Integer()),
    Column('Rate', DECIMAL(18, 2)),
    Column('Revenue', DECIMAL(18, 2)),
    Column('Inventory', Integer()),
    Column('Occperc', DECIMAL(18, 2))
)

snp_dbd_forecast_ml_model = Table(
    'snp_dbd_forecast_ml', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('AsOfDate', Date()),
    Column('Date', Date()),
    Column('Occupancy', Integer()),
    Column('Rate', DECIMAL(18, 2)),
    Column('Revenue', DECIMAL(18, 2)),
    Column('Inventory', Integer()),
    Column('Occperc', DECIMAL(18, 2))
)

snp_dynamic_pickup_model = Table(
    'snp_dynamic_pickup', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('AsOfDate', Date()),
    Column('PickUpDataJson', Text()),
)

snp_seven_day_chart_model = Table(
    'snp_seven_day_chart', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('AsOfDate', Date()),
    Column('Type', String(50)),
    Column('JsonData', Text())
)

pms_wise_opera_occ_model = Table(
    'pms_wise_opera_occ', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(20)),
    Column('AsOfDate', Date()),
    Column('REVENUE', String(55)),
    Column('NO_ROOMS', String(55)),
    Column('IND_DEDUCT_ROOMS', String(55)),
    Column('IND_NON_DEDUCT_ROOMS', String(55)),
    Column('GRP_DEDUCT_ROOMS', String(55)),
    Column('GRP_NON_DEDUCT_ROOMS', String(55)),
    Column('NO_PERSONS', String(55)),
    Column('ARRIVAL_ROOMS', String(55)),
    Column('DEPARTURE_ROOMS', String(55)),
    Column('COMPLIMENTARY_ROOMS', String(55)),
    Column('HOUSE_USE_ROOMS', String(55)),
    Column('DAY_USE_ROOMS', String(55)),
    Column('NO_SHOW_ROOMS', String(55)),
    Column('INVENTORY_ROOMS', String(55)),
    Column('CONSIDERED_DATE', String(55)),
    Column('CHAR_CONSIDERED_DATE', String(55)),
    Column('IND_DEDUCT_REVENUE', String(55)),
    Column('IND_NON_DEDUCT_REVENUE', String(55)),
    Column('GRP_NON_DEDUCT_REVENUE', String(55)),
    Column('GRP_DEDUCT_REVENUE', String(55)),
    Column('OWNER_ROOMS', String(55)),
    Column('FF_ROOMS', String(55)),
    Column('CF_OOO_ROOMS', String(55)),
    Column('CF_CALC_OCC_ROOMS', String(55)),
    Column('CF_CALC_INV_ROOMS', String(55)),
    Column('CF_AVERAGE_ROOM_RATE', String(55)),
    Column('CF_OCCUPANCY', String(55)),
    Column('CF_IND_DED_REV', String(55)),
    Column('CF_IND_NON_DED_REV', String(55)),
    Column('CF_BLK_DED_REV', String(55)),
    Column('CF_BLK_NON_DED_REV', String(55))
)

pms_wise_opera_res_model = Table(
    'pms_wise_opera_res', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(20)),
    Column('AsOfDate', Date()),
    Column('RESV_NAME_ID', String(55)),
    Column('GUARANTEE_CODE', String(55)),
    Column('RESV_STATUS', String(55)),
    Column('ROOM', String(55)),
    Column('FULL_NAME', String(55)),
    Column('DEPARTURE', String(55)),
    Column('PERSONS', String(55)),
    Column('GROUP_NAME', String(55)),
    Column('NO_OF_ROOMS', String(55)),
    Column('ROOM_CATEGORY_LABEL', String(55)),
    Column('RATE_CODE', String(55)),
    Column('INSERT_USER', String(55)),
    Column('INSERT_DATE', String(55)),
    Column('GUARANTEE_CODE_DESC', String(55)),
    Column('COMPANY_NAME', String(55)),
    Column('TRAVEL_AGENT_NAME', String(55)),
    Column('ARRIVAL', String(55)),
    Column('NIGHTS', String(55)),
    Column('COMP_HOUSE_YN', String(55)),
    Column('SHARE_AMOUNT', String(55)),
    Column('C_T_S_NAME', String(55)),
    Column('SHORT_RESV_STATUS', String(55)),
    Column('SHARE_AMOUNT_PER_STAY', String(55)),
)

snp_weekly_star_model = Table(
    'snp_weekly_star', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('AsOfDate', Date()),
    Column('StarReportDate', Date()),
    Column('OccMyProperty', DECIMAL(18, 2), nullable=True),
    Column('OccMyPropertyChange', DECIMAL(18, 2), nullable=True),
    Column('OccMyPropertyLy', DECIMAL(18, 2), nullable=True),
    Column('OccCompset', DECIMAL(18, 2), nullable=True),
    Column('OccCompsetChange', DECIMAL(18, 2), nullable=True),
    Column('OccCompsetLy', DECIMAL(18, 2), nullable=True),
    Column('OccIndex', DECIMAL(18, 2), nullable=True),
    Column('OccIndexChange', DECIMAL(18, 2), nullable=True),
    Column('OccIndexLy', DECIMAL(18, 2), nullable=True),
    Column('AdrMyProperty', DECIMAL(18, 2), nullable=True),
    Column('AdrMyPropertyChange', DECIMAL(18, 2), nullable=True),
    Column('AdrMyPropertyLy', DECIMAL(18, 2), nullable=True),
    Column('AdrCompset', DECIMAL(18, 2), nullable=True),
    Column('AdrCompsetChange', DECIMAL(18, 2), nullable=True),
    Column('AdrCompsetLy', DECIMAL(18, 2), nullable=True),
    Column('AdrIndex', DECIMAL(18, 2), nullable=True),
    Column('AdrIndexChange', DECIMAL(18, 2), nullable=True),
    Column('AdrIndexLy', DECIMAL(18, 2), nullable=True),
    Column('RevparMyProperty', DECIMAL(18, 2), nullable=True),
    Column('RevparMyPropertyChange', DECIMAL(18, 2), nullable=True),
    Column('RevparMyPropertyLy', DECIMAL(18, 2), nullable=True),
    Column('RevparCompset', DECIMAL(18, 2), nullable=True),
    Column('RevparCompsetChange', DECIMAL(18, 2), nullable=True),
    Column('RevparCompsetLy', DECIMAL(18, 2), nullable=True),
    Column('RevparIndex', DECIMAL(18, 2), nullable=True),
    Column('RevparIndexChange', DECIMAL(18, 2), nullable=True),
    Column('RevparIndexLy', DECIMAL(18, 2), nullable=True),
    Column('UpdatedOn', DateTime, onupdate=func.utc_timestamp()),
    Column('UpdatedBy', Integer, nullable=True)
)

snp_running_28_star_model = Table(
    'snp_running_28_star', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('AsOfDate', Date()),
    Column('Weekday', String(10)),
    Column('OccMyProperty', DECIMAL(18, 2), nullable=True),
    Column('OccMyPropertyChange', DECIMAL(18, 2), nullable=True),
    Column('OccMyPropertyLy', DECIMAL(18, 2), nullable=True),
    Column('OccCompset', DECIMAL(18, 2), nullable=True),
    Column('OccCompsetChange', DECIMAL(18, 2), nullable=True),
    Column('OccCompsetLy', DECIMAL(18, 2), nullable=True),
    Column('OccIndex', DECIMAL(18, 2), nullable=True),
    Column('OccIndexChange', DECIMAL(18, 2), nullable=True),
    Column('OccIndexLy', DECIMAL(18, 2), nullable=True),
    Column('AdrMyProperty', DECIMAL(18, 2), nullable=True),
    Column('AdrMyPropertyChange', DECIMAL(18, 2), nullable=True),
    Column('AdrMyPropertyLy', DECIMAL(18, 2), nullable=True),
    Column('AdrCompset', DECIMAL(18, 2), nullable=True),
    Column('AdrCompsetChange', DECIMAL(18, 2), nullable=True),
    Column('AdrCompsetLy', DECIMAL(18, 2), nullable=True),
    Column('AdrIndex', DECIMAL(18, 2), nullable=True),
    Column('AdrIndexChange', DECIMAL(18, 2), nullable=True),
    Column('AdrIndexLy', DECIMAL(18, 2), nullable=True),
    Column('RevparMyProperty', DECIMAL(18, 2), nullable=True),
    Column('RevparMyPropertyChange', DECIMAL(18, 2), nullable=True),
    Column('RevparMyPropertyLy', DECIMAL(18, 2), nullable=True),
    Column('RevparCompset', DECIMAL(18, 2), nullable=True),
    Column('RevparCompsetChange', DECIMAL(18, 2), nullable=True),
    Column('RevparCompsetLy', DECIMAL(18, 2), nullable=True),
    Column('RevparIndex', DECIMAL(18, 2), nullable=True),
    Column('RevparIndexChange', DECIMAL(18, 2), nullable=True),
    Column('RevparIndexLy', DECIMAL(18, 2), nullable=True),
    Column('UpdatedOn', DateTime, onupdate=func.utc_timestamp()),
    Column('UpdatedBy', Integer, nullable=True)
)

redroof_res_model = Table(
    'redroof_res', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(20)),
    Column('AsOfDate', Date()),
    Column('name', String(150)),
    Column('accountid', String(150)),
    Column('status', String(150)),
    Column('arrival', Date()),
    Column('departure', Date()),
    Column('gtd', String(150)),
    Column('companyaccount', String(150)),
    Column('source', String(150)),
    Column('crs', String(150)),
    Column('roomtype', String(150)),
    Column('room', String(150)),
    Column('rate', String(150)),
    Column('rateplan', String(150)),
    Column('companyid', String(150)),
    Column('balance', String(150)),
    Column('companyname', String(150)),
    Column('roomcount', String(150)),
    Column('adult', String(150)),
    Column('child', String(150)),
    Column('createdate', Date()),
    Column('padroom', String(150)),
    Column('phonenumber', String(150)),
    Column('accountuid', String(150)),
    Column('corpid', String(150)),
    Column('taname', String(150)),
    Column('loyallevel', String(150)),
    Column('frequentstay', String(150)),
    Column('receivablesname', String(150)),
    Column('groupid', String(150)),
    Column('groupname', String(150)),
    Column('groupaccount', String(150)),
    Column('vip', String(150)),
    Column('specialamount', String(150)),
    Column('specialtodate', String(20)),
    Column('specialcode', String(150)),
    Column('specialfolio', String(150)),
    Column('specialfromdate', String(20))
)

redroof_occ_model = Table(
    'redroof_occ', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(20)),
    Column('AsOfDate', Date()),
    Column('idate', Date()),
    Column('totalrooms', String(25)),
    Column('ooirooms', String(25)),
    Column('ooorooms', String(25)),
    Column('inhouse', String(25)),
    Column('stayovers', String(25)),
    Column('dueouts', String(25)),
    Column('gtdres', String(25)),
    Column('nongtdres', String(25)),
    Column('notpickedup', String(25)),
    Column('npuratetotal', String(25)),
    Column('roomrev', String(25)),
    Column('adults', String(25)),
    Column('children', String(25)),
    Column('currentadults', String(25)),
    Column('currentchildren', String(25)),
    Column('dayuseinhouse', String(25)),
    Column('rod', String(25))
)

redroof_monthly_summary_model = Table(
    'redroof_monthly_summary', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(20)),
    Column('AsOfDate', Date()),
    Column('businessdate', Date()),
    Column('rentedrooms', String(10)),
    Column('availablerooms', String(10)),
    Column('room', String(10))
)

pms_wise_redroof_res_model = Table(
    'pms_wise_redroof_res', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(20)),
    Column('AsOfDate', Date()),
    Column('name', String(150)),
    Column('accountid', String(150)),
    Column('status', String(150)),
    Column('arrival', Date()),
    Column('departure', Date()),
    Column('gtd', String(150)),
    Column('companyaccount', String(150)),
    Column('source', String(150)),
    Column('crs', String(150)),
    Column('roomtype', String(150)),
    Column('room', String(150)),
    Column('rate', String(150)),
    Column('rateplan', String(150)),
    Column('companyid', String(150)),
    Column('balance', String(150)),
    Column('companyname', String(150)),
    Column('roomcount', String(150)),
    Column('adult', String(150)),
    Column('child', String(150)),
    Column('createdate', Date()),
    Column('padroom', String(150)),
    Column('phonenumber', String(150)),
    Column('accountuid', String(150)),
    Column('corpid', String(150)),
    Column('taname', String(150)),
    Column('loyallevel', String(150)),
    Column('frequentstay', String(150)),
    Column('receivablesname', String(150)),
    Column('groupid', String(150)),
    Column('groupname', String(150)),
    Column('groupaccount', String(150)),
    Column('vip', String(150)),
    Column('specialamount', String(150)),
    Column('specialtodate', String(20)),
    Column('specialcode', String(150)),
    Column('specialfolio', String(150)),
    Column('specialfromdate', String(20))
)
pms_wise_redroof_occ_model = Table(
    'pms_wise_redroof_occ', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(20)),
    Column('AsOfDate', Date()),
    Column('idate', Date()),
    Column('totalrooms', String(25)),
    Column('ooirooms', String(25)),
    Column('ooorooms', String(25)),
    Column('inhouse', String(25)),
    Column('stayovers', String(25)),
    Column('dueouts', String(25)),
    Column('gtdres', String(25)),
    Column('nongtdres', String(25)),
    Column('notpickedup', String(25)),
    Column('npuratetotal', String(25)),
    Column('roomrev', String(25)),
    Column('adults', String(25)),
    Column('children', String(25)),
    Column('currentadults', String(25)),
    Column('currentchildren', String(25)),
    Column('dayuseinhouse', String(25)),
    Column('rod', String(25))
)

pms_wise_redroof_monthly_summary_model = Table(
    'pms_wise_redroof_monthly_summary', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(20)),
    Column('AsOfDate', Date()),
    Column('businessdate', Date()),
    Column('rentedrooms', String(10)),
    Column('availablerooms', String(10)),
    Column('room', String(10))
)

idb_res_model = Table(
    'idb_res', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(20)),
    Column('AsOfDate', Date()),
    Column('contactEmail', String(255)),
    Column('contactNo', String(50)),
    Column('bookingName', Text()),
    Column('blockCode', String(255)),
    Column('arrivalDate', String(20)),
    Column('guestName', String(255)),
    Column('reservationDate', String(20)),
    Column('segment', String(255)),
    Column('remarks', Text()),
    Column('departureDate', String(20)),
    Column('billingInstruc', String(255)),
    Column('bookingNo', String(20)),
    Column('source', String(255)),
    Column('contactPpl', String(255)),
    Column('specialReq', Text()),
    Column('travelAgent', String(255)),
    Column('trxAmount', String(20)),
    Column('noOfNight', String(20)),
    Column('noOfRoom', String(20)),
    Column('roomType', String(255)),
    Column('rateCode', String(255))
)

idb_occ_model = Table(
    'idb_occ', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(20)),
    Column('AsOfDate', Date()),
    Column('Mode', String(20)),
    Column('Date', String(20)),
    Column('TotalOcc', String(20)),
    Column('ArrRooms', String(20)),
    Column('CompRooms', String(20)),
    Column('HouseUse', String(20)),
    Column('DedIndiv', String(20)),
    Column('NonDedIndiv', String(20)),
    Column('DedGroup', String(20)),
    Column('NonDedGroup', String(20)),
    Column('Occ', String(20)),
    Column('TentativeOcc', String(20)),
    Column('RoomRevenue', String(20)),
    Column('AverageRate', String(20)),
    Column('DepRooms', String(20)),
    Column('DayUseRooms', String(20)),
    Column('NoShowRooms', String(20)),
    Column('OOORooms', String(20)),
    Column('AdlnChil', String(20))
)

pms_wise_idb_res_model = Table(
    'pms_wise_idb_res', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(20)),
    Column('AsOfDate', Date()),
    Column('contactEmail', String(255)),
    Column('contactNo', String(50)),
    Column('bookingName', Text()),
    Column('blockCode', String(255)),
    Column('arrivalDate', String(20)),
    Column('guestName', String(255)),
    Column('reservationDate', String(20)),
    Column('segment', String(255)),
    Column('remarks', Text()),
    Column('departureDate', String(20)),
    Column('billingInstruc', String(255)),
    Column('bookingNo', String(20)),
    Column('source', String(255)),
    Column('contactPpl', String(255)),
    Column('specialReq', Text()),
    Column('travelAgent', String(255)),
    Column('trxAmount', String(20)),
    Column('noOfNight', String(20)),
    Column('noOfRoom', String(20)),
    Column('roomType', String(255)),
    Column('rateCode', String(255))
)

pms_wise_idb_occ_model = Table(
    'pms_wise_idb_occ', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(20)),
    Column('AsOfDate', Date()),
    Column('Mode', String(20)),
    Column('Date', String(20)),
    Column('TotalOcc', String(20)),
    Column('ArrRooms', String(20)),
    Column('CompRooms', String(20)),
    Column('HouseUse', String(20)),
    Column('DedIndiv', String(20)),
    Column('NonDedIndiv', String(20)),
    Column('DedGroup', String(20)),
    Column('NonDedGroup', String(20)),
    Column('Occ', String(20)),
    Column('TentativeOcc', String(20)),
    Column('RoomRevenue', String(20)),
    Column('AverageRate', String(20)),
    Column('DepRooms', String(20)),
    Column('DayUseRooms', String(20)),
    Column('NoShowRooms', String(20)),
    Column('OOORooms', String(20)),
    Column('AdlnChil', String(20))
)

# meta.create_all(engine)
