import enum
from enum import Enum


class SEVEN_DAY_CHART_TYPE(Enum):
    SEVEN_DAY_BOOKING_ROOMS = "SEVEN_DAY_BOOKING_ROOMS"
    SEVEN_DAY_BOOKING_PACE = "SEVEN_DAY_BOOKING_PACE"
    SEVEN_WEEK_BOOKING_PACE = "SEVEN_WEEK_BOOKING_PACE"
    SEVEN_DAY_BOOKING_EXPECTED = "SEVEN_DAY_BOOKING_EXPECTED"


class ENUM_JOB_STATUS(enum.Enum):
    SUCCESS = "SUCCESS"
    INPROCESS = "INPROCESS"
    FAILED = "FAILED"


class ENUM_JOB_TYPE(enum.Enum):
    PMS_REPORT = "PMS_REPORT"
    RATE_SHOP = "RATE_SHOP"
    EVENT = "EVENT"
    STAR_REPORT = "STAR_REPORT"
    EMA_LOG = "EMA_LOG"


class ENUM_PROCESS_TYPE(enum.Enum):
    PULL_REPORT = "PULL_REPORT"
    REPORT_TO_UNI_RES = "REPORT_TO_UNI_RES"
    REPORT_TO_UNI_OCC = "REPORT_TO_UNI_OCC"
    CREATE_WIDGET = "CREATE_WIDGET"
    PULL_STAR_REPORT = "PULL_STAR_REPORT"
    COPY_OLD_DATA = "COPY_OLD_DATA"
    EMA_LOG = "EMA_LOG"